CREATE SEQUENCE s3
START WITH 1 
INCREMENT BY 1 
MAXVALUE 10;
 
select s3.NEXTVAL from DUAL;
 
select s3.NEXTVAL from DUAL;
 
select s3.NEXTVAL from DUAL;
 
select s3.CURRVAL from DUAL;
 

SELECT ROWID,EMP_ID,EMP_NAME FROM EMPLOYEE;
 
SELECT EMP_ID,EMP_NAME,rownum FROM EMPLOYEE;
 
